spring:
  application:
    name: nutrilabel-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nutrilabel}
    username: ${DB_USER:nutri}
    password: ${DB_PASSWORD:nutri}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
  jackson:
    generator:
      write-bigdecimal-as-plain: true

server:
  port: 8080
